name: Deploy Book

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'code/**'
    branches:
      - main

jobs:
  build:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Install mdBook
        run: curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=/usr/local/bin

      - name: Build Book
        run: mdbook build

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: book
          branch: gh-pages
